# Generated by Django 3.2.1 on 2024-10-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_aboutme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='education',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='skills',
            field=models.TextField(max_length=255),
        ),
    ]
