# Generated by Django 3.2.1 on 2024-10-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20241011_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='contact',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
